name = "Polygon"
uuid = "6c90dff6-b80f-4bd2-aa9c-319c6ebead32"
authors = ["Sebastian Rollen <rollenseb@gmail.com>"]
version = "1.0.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
