name: CompatHelper

on:
  schedule:
    - cron: '07 * * * *'

jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.3
      - name: Pkg.add("CompatHelper")
        run: julia -e 'using Pkg; Pkg.add("CompatHelper")'
      - name: CompatHelper.main()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia -e 'my_registries = [Pkg.RegistrySpec(name = "General",
                                  uuid = "23338594-aafe-5451-b93e-139f81909106",
                                  url = "https://github.com/JuliaRegistries/General.git"),
                 Pkg.RegistrySpec(name = "PrivateRegistry",
                                  uuid = "c8caab24-3583-11ea-11d4-c5acbea233a5",
                                  url = "git@github.com:HakoSwede/PrivateRegistry.git")];
                 using CompatHelper; CompatHelper.main(; registries = my_registries)'
